version: "3.8"
services:

    valentina:
        build: C:\Users\vidri\Documents\Residencias\galaxy-classifier-api-valentina
        volumes: 
            - C:\Users\vidri\Documents\Residencias\galaxy-classifier-api-valentina:/usr/src/app
            - /usr/src/app/node_modules
        networks: 
            - valentinanet
        expose:
            - "4001"
    
    pedro:
        build: .
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on: 
            - valentina
            # - sofia
            # - database
            # - redis
        ports:
            - "5001:5001"
        networks: 
            - valentinanet
            # - persistence
            # - sofianet
            # - valentinanet
        environment: 
            # - POSTGRESQL_USERNAME=
            # - POSTGRESQL_PASSWORD=
            # - POSTGRESQL_DATABASE=
            # - REDIS_PASSWORD=
            - VALENTINA_PORT=4001
            - VALENTINA_HOST=valentina
            # - SOFIA_PORT=5001
    
    # sofia:
    #     build: {path_to_sofia_dockerfile}
    #     networks: sofianet
    
    # database:
    #     image: bitnami/postgresql:12.3.0
    #     environment: 
    #         - POSTGRESQL_USERNAME=
    #         - POSTGRESQL_PASSWORD=
    #         - POSTGRESQL_DATABASE=
    #     ports:
    #         - "5432:5432"
    #     networks: persistence
    
    # redis:
    #     image: bitnami/redis:5.0.9
    #     environment:
    #         - REDIS_PASSWORD=
    #     networks: persistence

networks:
    # persistence:
    #     driver: bridge
    # sofianet:
    #     driver: bridge
    valentinanet:
        driver: bridge